const blogs = [
  {
    slug: 'why-i-want-to-be-a-doctor',
    title: 'Why I Want to Be a Doctor',
    date: '2025-11-10',
    readTime: '4 min',
    category: 'Medicine',
    excerpt: 'Growing up in Jhapa, I saw what lack of access to care can do to a family. This is the story of why I chose medicine.',
    file: () => import('./why-i-want-to-be-a-doctor.md?raw'),
  },
  {
    slug: 'total-darkness',
    title: 'Total Darkness',
    date: '2026-07-10',
    readTime: '2 min',
    category: 'Poetry',
    excerpt: 'With trembling hands, after hours of rush, a heartbeat was heard... A poem reflecting on the exhaustion and triumph after saving a young soul.',
    file: () => import('./total-darkness.md?raw'),
  },
  {
    slug: 'lub-dub-lub-dub',
    title: 'Lub-dub, lub-dub',
    date: '2026-05-20',
    readTime: '2 min',
    category: 'Poetry',
    excerpt: 'Lub-dub, lub-dub, The cardiac valves closing... A poem on facing the primary trial of the first incision.',
    file: () => import('./lub-dub-lub-dub.md?raw'),
  },
  {
    slug: 'the-color-of-happiness',
    title: 'The Color of Happiness',
    date: '2026-04-05',
    readTime: '2 min',
    category: 'Poetry',
    excerpt: 'The color of happiness is white, or so I choose to believe... A poem on the weight, passion, and calling to heal.',
    file: () => import('./the-color-of-happiness.md?raw'),
  },
  {
    slug: 'the-human-heart',
    title: 'The Human Heart: More Than a Pump',
    date: '2025-10-22',
    readTime: '5 min',
    category: 'Biology',
    excerpt: 'A deep dive into the anatomy and poetry hidden inside the most vital organ in the human body.',
    file: () => import('./the-human-heart.md?raw'),
  },
  {
    slug: 'poetry-and-medicine',
    title: 'On Writing Poetry and Studying Medicine',
    date: '2025-09-14',
    readTime: '3 min',
    category: 'Writing',
    excerpt: 'Two disciplines that seem apart but are rooted in the same need: to understand the human condition.',
    file: () => import('./poetry-and-medicine.md?raw'),
  },
]

export default blogs